#!/usr/bin/env python3
"""Build the single-domain TraderHome demo from the three product snapshots."""
from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PORTAL = ROOT / "portal"
SHELL_CSS = '<link rel="stylesheet" href="/assets/traderhome-shell.css" data-traderhome-shell="v3">'
SHELL_JS = '<script src="/assets/traderhome-shell.js" data-traderhome-shell="v3" defer></script>'
THEME_COLOR = '<meta name="theme-color" content="#070b14">'
FAVICON = (
    '<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 '
    'viewBox=%270 0 64 64%27%3E%3Crect width=%2764%27 height=%2764%27 rx=%2714%27 '
    'fill=%27%23070b14%27/%3E%3Cpath d=%27M12 19h20M22 19v28M38 19v28M38 33h14M52 19v28%27 '
    'stroke=%27%2367e8f9%27 stroke-width=%276%27 stroke-linecap=%27round%27/%3E%3C/svg%3E">'
)
DOMAIN = "https://traderhome-histroy.xyz"
CANONICAL_ROUTES = {
    "index.html": "/",
    "history/index.html": "/history/",
    "decision/index.html": "/decision/",
    "decision/app.html": "/decision/app.html",
    "decision/tos.html": "/decision/tos.html",
    "review/index.html": "/review/",
    "standards/index.html": "/standards/",
}


def _copy_file(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def _inject_shell(path: Path, output: Path) -> None:
    html = path.read_text(encoding="utf-8")
    if "</head>" not in html.lower() or "</body>" not in html.lower():
        raise ValueError(f"HTML shell anchors missing: {path}")
    rel = path.relative_to(output).as_posix()
    route = CANONICAL_ROUTES.get(rel)
    canonical = DOMAIN + route if route else None
    head_extras = []
    if 'name="theme-color"' not in html.lower():
        head_extras.append(THEME_COLOR)
    if 'rel="icon"' not in html.lower():
        head_extras.append(FAVICON)
    if canonical:
        if 'rel="canonical"' not in html.lower():
            head_extras.append(f'<link rel="canonical" href="{canonical}">')
        html = re.sub(
            r'(<meta\s+property=["\']og:url["\']\s+content=["\'])[^"\']*(["\'])',
            rf"\g<1>{canonical}\2", html, flags=re.I,
        )
    if rel == "history/index.html":
        html = html.replace(f"{DOMAIN}/og.png", f"{DOMAIN}/history/og.png")
    if head_extras:
        head_at = html.lower().rfind("</head>")
        html = html[:head_at] + "  " + "\n  ".join(head_extras) + "\n" + html[head_at:]
    if 'data-traderhome-shell="v3"' in html:
        path.write_text(html, encoding="utf-8")
        return
    lower = html.lower()
    head_at = lower.rfind("</head>")
    html = html[:head_at] + "  " + SHELL_CSS + "\n" + html[head_at:]
    lower = html.lower()
    body_at = lower.rfind("</body>")
    html = html[:body_at] + "  " + SHELL_JS + "\n" + html[body_at:]
    path.write_text(html, encoding="utf-8")


def build(output: Path) -> dict:
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)

    _copy_file(PORTAL / "home" / "index.html", output / "index.html")
    _copy_file(PORTAL / "home" / "standards.html", output / "standards" / "index.html")
    shutil.copytree(PORTAL / "assets", output / "assets")

    # Kezhou stays generated by its daily pipeline; only its location changes.
    _copy_file(ROOT / "prototype" / "app.html", output / "history" / "index.html")
    if (ROOT / "prototype" / "og.png").exists():
        _copy_file(ROOT / "prototype" / "og.png", output / "history" / "og.png")

    # Browser-safe snapshots. No private TradeReview trade ledger is published.
    shutil.copytree(PORTAL / "vendor" / "decision", output / "decision")
    shutil.copytree(PORTAL / "vendor" / "review", output / "review")

    for html in output.rglob("*.html"):
        _inject_shell(html, output)

    for name in ("CNAME", "DISCLAIMER.md"):
        source = ROOT / name
        if source.exists():
            _copy_file(source, output / name)

    manifest = {
        "name": "TraderHome",
        "version": 3,
        "routes": {
            "home": "/",
            "history": "/history/",
            "decision": "/decision/app.html",
            "review": "/review/",
            "standards": "/standards/",
        },
        "productContracts": {
            "history": {"output": "probability_edge_interval_robustness", "rejects": "stale_or_weak_evidence"},
            "decision": {"output": "trigger_entry_invalidation_target_r", "rejects": "direction_location_or_rr_gate"},
            "review": {"output": "costly_behavior_evidence_trade_one_action_growth", "rejects": "insufficient_evidence"},
        },
        "evidenceLabels": ["DATA", "DERIVED", "FORWARD", "METHOD_DEMO"],
        "privacy": {"privateTradeLedgerPublished": False, "reviewDemo": "synthetic"},
    }
    (output / "traderhome-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "_site")
    args = parser.parse_args()
    manifest = build(args.output.resolve())
    print(f"Built TraderHome routes: {', '.join(manifest['routes'].values())}")


if __name__ == "__main__":
    main()
