#!/usr/bin/env python3
"""Build the single-domain TraderHome demo from the three product snapshots."""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PORTAL = ROOT / "portal"
SHELL_CSS = '<link rel="stylesheet" href="/assets/traderhome-shell.css" data-traderhome-shell="v1">'
SHELL_JS = '<script src="/assets/traderhome-shell.js" data-traderhome-shell="v1" defer></script>'


def _copy_file(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def _inject_shell(path: Path) -> None:
    html = path.read_text(encoding="utf-8")
    if 'data-traderhome-shell="v1"' in html:
        return
    if "</head>" not in html.lower() or "</body>" not in html.lower():
        raise ValueError(f"HTML shell anchors missing: {path}")
    lower = html.lower()
    head_at = lower.rfind("</head>")
    html = html[:head_at] + "  " + SHELL_CSS + "\n" + html[head_at:]
    lower = html.lower()
    body_at = lower.rfind("</body>")
    html = html[:body_at] + "  " + SHELL_JS + "\n" + html[body_at:]
    path.write_text(html, encoding="utf-8")


def build(output: Path) -> dict:
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)

    _copy_file(PORTAL / "home" / "index.html", output / "index.html")
    shutil.copytree(PORTAL / "assets", output / "assets")

    # Kezhou stays generated by its daily pipeline; only its location changes.
    _copy_file(ROOT / "prototype" / "app.html", output / "history" / "index.html")
    if (ROOT / "prototype" / "og.png").exists():
        _copy_file(ROOT / "prototype" / "og.png", output / "history" / "og.png")

    # Browser-safe snapshots. No private TradeReview trade ledger is published.
    shutil.copytree(PORTAL / "vendor" / "decision", output / "decision")
    shutil.copytree(PORTAL / "vendor" / "review", output / "review")

    for html in output.rglob("*.html"):
        _inject_shell(html)

    for name in ("CNAME", "DISCLAIMER.md"):
        source = ROOT / name
        if source.exists():
            _copy_file(source, output / name)

    manifest = {
        "name": "TraderHome",
        "version": 1,
        "routes": {
            "home": "/",
            "history": "/history/",
            "decision": "/decision/app.html",
            "review": "/review/",
        },
        "privacy": {"privateTradeLedgerPublished": False},
    }
    (output / "traderhome-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "_site")
    args = parser.parse_args()
    manifest = build(args.output.resolve())
    print(f"Built TraderHome routes: {', '.join(manifest['routes'].values())}")


if __name__ == "__main__":
    main()
